//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikiDataExtractor.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WikiDataExtractor.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{Infobox settlement
        ///| name                            = Warsaw
        ///| native_name                     = &amp;lt;small&amp;gt;&apos;&apos;Warszawa&apos;&apos;&amp;lt;/small&amp;gt;
        ///| native_name_lang                = pl
        ///| settlement_type                 = [[City with powiat rights|Capital city and county]]
        ///| image_skyline                   = {{Photomontage|
        /// |color=#ffffff
        /// |photo1a = Aleja Niepdleglosci Warsaw 2022 aerial (cropped).jpg
        /// |photo2a = Pałac Na Wyspie w Warszawie, widok na elewację południową.jpg
        /// |photo2b = Poland-00808 - Ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wikitext1 {
            get {
                return ResourceManager.GetString("wikitext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{For|the name of Warsaw in various languages|wikt:Warsaw}}
        ///
        ///== Geography ==
        ///Warsaw is near the middle of Poland on both sides of the Vistula [[river]], and about 350 [[kilometre|km]] (225 [[mile]]s) from the [[Baltic Sea]]. It is about 100 [[metre|m]] (325 [[Foot (unit of length)|ft]]) above [[sea level]]. Warsaw has a [[humid continental climate]] (&apos;&apos;Dfb&apos;&apos; in the [[Koeppen climate classification]]).
        ///
        ///Warsaw is home to four [[university|universities]] and 62 [[college]]s, and many [[theatre]]s and art [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wikitext2 {
            get {
                return ResourceManager.GetString("wikitext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Parent&gt;
        ///  &lt;element&gt;
        ///    &lt;node type=&quot;empty&quot;&gt;&lt;/node&gt;
        ///  &lt;/element&gt;
        ///  &lt;text&gt;1&lt;/text&gt;
        ///  &lt;text&gt;2&lt;/text&gt;
        ///  &lt;anotherText&gt;3&lt;/anotherText&gt;
        ///&lt;/Parent&gt;.
        /// </summary>
        internal static string xml_text_nodes {
            get {
                return ResourceManager.GetString("xml_text_nodes", resourceCulture);
            }
        }
    }
}
